version: "2"
services:
  app:
    container_name: archiveloader-app
    restart: always
    build: .
    ports:
      - "8989:8989"
    links:
      - mongo
    environment:
      - NODE_ENV=production
    env_file:
      - ./services.env
  mongo:
    container_name: archiveloader-mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - 'archiveloader-data:/data/db'
volumes: 
  archiveloader-data: