version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8989:8989"
    links:
      - mongo
    environment:
      - NODE_ENV=production
    env_file:
      - ./services.env
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"